#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-tailscale-install() {
    pull-docker-image() {
        declare IMAGE="$1"
        if [[ "$PLUGIN_DISABLE_PULL" == "true" ]]; then
        echo " !     ${PLUGIN_DISABLE_PULL_VARIABLE} environment variable detected. Not running pull command." 1>&2
        echo " !        docker image pull ${IMAGE}" 1>&2
        return
        fi
        if [[ "$("$DOCKER_BIN" image ls -q "${IMAGE}" 2>/dev/null)" == "" ]]; then
        "$DOCKER_BIN" image pull "${IMAGE}"
        fi
    }
    pull-docker-image "${PLUGIN_TAILSCALE_IMAGE}"
    storagedir="${DOKKU_LIB_ROOT}/data/tailscale"
    mkdir -p "${storagedir}"

    # Install is potentially done by root.
    chown dokku:dokku "${storagedir}"
}

trigger-tailscale-install "$@"
